=pod

=encoding utf-8

=head1 NAME

Type::Tiny::Manual - an overview of Type::Tiny

=head1 SYNOPSIS

L<Type::Tiny> is a small class for writing type constraints, inspired by
L<Moose>'s type constraint API. It has no non-core dependencies, and can be
used with L<Moose>, L<Mouse> and L<Moo> (or none of the above).

Type::Tiny is bundled with L<Type::Library> a framework for organizing type
constraints into collections.

Also bundled is L<Types::Standard>, a Moose-inspired library of useful type
constraints.

L<Type::Params> is also provided, to allow very fast checking and coercion
of function and method parameters.

=head1 SEE ALSO

=over

=item *

L<Libraries|Type::Tiny::Manual::Libraries> - how to build a type library with Type::Tiny, Type::Library and Type::Utils

=item *

L<Coercions|Type::Tiny::Manual::Coercions> - adding coercions to type constraints

=item *

L<Using with Moose|Type::Tiny::Manual::UsingWithMoose> - how to use Type::Tiny and Type::Library with Moose

=item *

L<Using with Mouse|Type::Tiny::Manual::UsingWithMouse> - how to use Type::Tiny and Type::Library with Mouse

=item *

L<Using with Moo|Type::Tiny::Manual::UsingWithMoo> - how to use Type::Tiny and Type::Library with Moo

=item *

L<Using with Other OO Frameworks|Type::Tiny::Manual::UsingWithOther> - how to use Type::Tiny and Type::Library with other OO frameworks

=item *

Type::Tiny and friends don't need to be used within an OO framework. See L<FreeMind::Node> for an example that does not.

=item *

L<Processing arguments to subs|Type::Tiny::Manual::Params> - coerce and validate arguments to functions and methods.

=back

=head1 TYPE::TINY VERSUS X

=head2 Specio 

Type::Tiny is similar in aim to L<Specio>. The major differences are that
Type::Tiny is "tiny"; and Type::Tiny dispenses with the idea of a type
registry and stringy access to type constraints.

=head2 MooseX::Types

Type::Tiny libraries expose a similar interface to L<MooseX::Types> libraries.
In most cases you should be able to rewrite a L<MooseX::Types> library to
use Type::Tiny pretty easily.

=head2 MooX::Types::MooseLike

Type::Tiny is faster and supports coercions.

=head2 Scalar::Does

L<Scalar::Does> is somewhat of a precursor to Type::Tiny, but has now been
rewritten to use Type::Tiny internally.

It gives you a C<< does($value, $type) >> function that is roughly equivalent
to C<< $type->check($value) >> except that C<< $type >> may be one of a list
of pre-defined strings (instead of a Type::Tiny type constraint); or may be
a package name in which case it will be assumed to be a role and checked with
C<< $value->DOES($type) >>.

=head1 BUGS

Please report any bugs to
L<http://rt.cpan.org/Dist/Display.html?Queue=Type-Tiny>.

=head1 SUPPORT

B<< IRC: >> support is available through in the I<< #moose >> channel
on L<irc.perl.org|http://www.irc.perl.org/channels.html>. If Type::Tiny
discussion there becomes overwhelming (unlikely) then I'll move it
to a separate channel.

=head1 AUTHOR

Toby Inkster E<lt>tobyink@cpan.orgE<gt>.

=head1 COPYRIGHT AND LICENCE

This software is copyright (c) 2013 by Toby Inkster.

This is free software; you can redistribute it and/or modify it under
the same terms as the Perl 5 programming language system itself.

=head1 DISCLAIMER OF WARRANTIES

THIS PACKAGE IS PROVIDED "AS IS" AND WITHOUT ANY EXPRESS OR IMPLIED
WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF
MERCHANTIBILITY AND FITNESS FOR A PARTICULAR PURPOSE.

=cut
